version: "3.8"

services:
  nginx:
    container_name: nginx
    build: ./srcs/requirements/nginx/
    ports:
      - 8080:80
  wordpress:
    container_name: wordpress
    build: ./srcs/requirements/wordpress/
